# Generated by Django 3.1 on 2020-10-07 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0002_auto_20201007_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='is_accepted',
            field=models.BooleanField(default=False, verbose_name='Is Accepted'),
        ),
    ]
