# Generated by Django 3.1 on 2020-10-11 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_auth',
            field=models.BooleanField(default=False, verbose_name='Email Authentication'),
        ),
    ]
