# Generated by Django 3.1 on 2020-10-31 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='tag',
            new_name='title',
        ),
    ]
