# Generated by Django 3.1 on 2020-10-01 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201001_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='hourly_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Hourly Prize'),
        ),
    ]
