# Generated by Django 3.1 on 2020-09-21 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200920_2122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='hourly_prize',
            new_name='hourly_price',
        ),
    ]
