# Generated by Django 3.1 on 2020-10-16 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201015_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='skill',
            field=models.ManyToManyField(blank=True, null=True, to='accounts.Skill'),
        ),
    ]
