# Generated by Django 3.1 on 2020-10-01 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20201001_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_auth',
            field=models.BooleanField(default=False, verbose_name='Email Verification'),
        ),
    ]
