# Generated by Django 3.1 on 2020-10-21 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20201016_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='skill',
            field=models.ManyToManyField(blank=True, to='accounts.Skill'),
        ),
    ]
