# Generated by Django 3.1 on 2020-09-22 11:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_type', models.CharField(max_length=50, verbose_name='Currency')),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_type', models.CharField(max_length=50, verbose_name='Level')),
            ],
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('description', models.TextField(blank=True, null=True)),
                ('price_type', models.CharField(choices=[(1, 'Hourly work'), (2, 'Periodic works')], default='1', max_length=50, verbose_name='price_type')),
                ('price_min', models.PositiveIntegerField(verbose_name='Minimum Price')),
                ('price_max', models.PositiveIntegerField(verbose_name='Maximum Price')),
                ('admit_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('status', models.CharField(choices=[(1, 'Project is aviable.'), (2, 'Work on it.'), (3, 'Project has been canceled. '), (4, 'Paid. ')], max_length=250, verbose_name='status')),
                ('skills', models.CharField(max_length=50, verbose_name='skills')),
                ('upload_files', models.FileField(upload_to='media/')),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.currency')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.level')),
            ],
        ),
    ]
