# Generated by Django 3.1 on 2020-09-19 19:45

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_type', models.CharField(choices=[(1, 'AZE'), (2, 'USA')], default=1, max_length=50, verbose_name='Currency')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('short_description', models.TextField(help_text='this text show to other users', max_length=1000)),
                ('long_description', models.TextField(blank=True, null=True)),
                ('price_type', models.CharField(choices=[(1, 'Hourly work'), (2, 'Periodic works')], default='1', max_length=50, verbose_name='price_type')),
                ('price_min', models.PositiveIntegerField(verbose_name='Minimum Price')),
                ('price_max', models.PositiveIntegerField(verbose_name='Maximum Price')),
                ('level', models.CharField(choices=[(1, 'Entry Level'), (1, 'Intermediate'), (1, 'Expert')], default='1', max_length=150, verbose_name='level')),
                ('admit_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('status', models.CharField(choices=[(1, 'Project is aviable.'), (1, 'Work on it.'), (1, 'Project has been canceled. '), (1, 'Paid. ')], max_length=250, verbose_name='status')),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.currency')),
            ],
        ),
    ]
