# Generated by Django 3.1 on 2020-09-20 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to='documents/%Y/%m/%d')),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='level',
            field=models.CharField(choices=[(1, 'Entry Level'), (2, 'Intermediate'), (3, 'Expert')], default='1', max_length=150, verbose_name='level'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[(1, 'Project is aviable.'), (2, 'Work on it.'), (3, 'Project has been canceled. '), (4, 'Paid. ')], max_length=250, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='project',
            name='upload_file',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.upload'),
            preserve_default=False,
        ),
    ]
