# Generated by Django 3.1 on 2020-10-30 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='proposals',
            field=models.ManyToManyField(related_name='news', to='home.Replies'),
        ),
    ]
