# Generated by Django 3.1 on 2020-10-13 13:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='admit_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
