# Generated by Django 3.1 on 2020-09-22 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='price_type',
            field=models.IntegerField(choices=[(1, 'Hourly work'), (2, 'Periodic works')], default=1, verbose_name='price_type'),
        ),
    ]
