# Generated by Django 3.1 on 2020-10-28 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricetype',
            name='price_type',
            field=models.CharField(max_length=50, verbose_name='Price Type'),
        ),
    ]
