# Generated by Django 3.1 on 2020-09-29 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='skills',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.skill'),
        ),
        migrations.AlterField(
            model_name='proposals',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='home.project'),
        ),
    ]
