# Generated by Django 3.1 on 2020-09-20 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200920_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='docfile',
            field=models.FileField(upload_to='media/'),
        ),
    ]
