# Generated by Django 3.1 on 2020-10-07 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20201003_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replies',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='home.project'),
        ),
    ]
