# Generated by Django 3.1 on 2020-11-04 21:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20201031_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='admit_time',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
