# Generated by Django 3.1 on 2020-10-10 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20201007_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='admit_time',
            field=models.DateTimeField(),
        ),
    ]
