# Generated by Django 3.1 on 2020-09-29 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200925_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='price_max',
        ),
        migrations.RemoveField(
            model_name='project',
            name='price_min',
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.project')),
            ],
        ),
    ]
