# Generated by Django 3.1 on 2020-09-20 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200920_2357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='upload_file',
        ),
    ]
