# Generated by Django 3.1 on 2020-09-29 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200929_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='price_max',
            field=models.PositiveIntegerField(default=1, verbose_name='Maximum Price'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='price_min',
            field=models.PositiveIntegerField(default=1, verbose_name='Minimum Price'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Price',
        ),
    ]
