# Generated by Django 3.1 on 2020-09-20 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_project_upload_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='upload_files',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.upload'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='currency',
            name='currency_type',
            field=models.CharField(default=1, max_length=50, verbose_name='Currency'),
        ),
    ]
