# Generated by Django 3.1 on 2020-10-26 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_new_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news', to='home.project'),
        ),
        migrations.AlterField(
            model_name='new',
            name='proposals',
            field=models.ManyToManyField(blank=True, null=True, related_name='news', to='home.Proposals'),
        ),
    ]
