# Generated by Django 3.1 on 2020-09-20 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200921_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='upload_files',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.upload'),
        ),
    ]
