# Generated by Django 3.1 on 2020-10-26 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20201026_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='proposals',
            field=models.ManyToManyField(blank=True, null=True, related_name='news', to='home.Replies'),
        ),
    ]
