# Generated by Django 3.1 on 2020-09-20 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200921_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='skills',
            field=models.CharField(default=1, max_length=50, verbose_name='skills'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='project',
            name='upload_files',
        ),
        migrations.AddField(
            model_name='project',
            name='upload_files',
            field=models.ManyToManyField(to='home.Upload'),
        ),
    ]
