# Generated by Django 3.1 on 2020-09-20 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20200921_0019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='upload_files',
        ),
        migrations.AddField(
            model_name='project',
            name='upload_files',
            field=models.FileField(default=1, upload_to='media/'),
            preserve_default=False,
        ),
    ]
